version: '3'
services:
  bdd:
    container_name: mysqlSortir
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: enieni
      MYSQL_DATABASE: sortirdb
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - bdd-sortir:/var/lib/mysql

volumes:
  bdd-sortir:
